require('dotenv').config();

module.exports = {
  development: {
    username: process.env.DATABASE_USER || 'postgres',
    password: process.env.DATABASE_PASSWORD || 'postgres',
    database: process.env.DATABASE_NAME || 'localhost:5432',
    host: process.env.DATABASE_HOST || 'Yallahood_local_db',
    dialect: 'postgres',
    seederStorage: 'sequelize',
    port: process.env.DATABASE_PORT || '5432',
    pool: {
      max: 20,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
    logging: true,
    encryptionKey: process.env.ENCRYPTION_KEY || 'test',
  },
  test: {
    username: process.env.DATABASE_USER || 'test',
    password: process.env.DATABASE_PASSWORD || 'test',
    database: process.env.DATABASE_NAME || 'testapp',
    host: process.env.DATABASE_HOST || 'localhost',
    dialect: 'postgres',
    seederStorage: 'sequelize',
    port: process.env.DATABASE_PORT || '5432',
    pool: {
      max: 20,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
    logging: true,
    encryptionKey: process.env.ENCRYPTION_KEY || 'test',
  },
  production: {
    username: process.env.DATABASE_USER || 'test',
    password: process.env.DATABASE_PASSWORD || 'test',
    database: process.env.DATABASE_NAME || 'testapp',
    host: process.env.DATABASE_HOST || 'localhost',
    dialect: 'postgres',
    seederStorage: 'sequelize',
    port: process.env.DATABASE_PORT || '5432',
    logging: false,
    pool: {
      max: 20,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
    encryptionKey: process.env.ENCRYPTION_KEY || 'test',
  },
  staging: {
    username: process.env.DATABASE_USER || 'test',
    password: process.env.DATABASE_PASSWORD || 'test',
    srcDatabase: process.env.DATABASE_NAME || 'testapp',
    database: process.env.TEST_DATABASE_NAME || 'canvas_unittest',
    host: process.env.DATABASE_HOST || 'localhost',
    dialect: 'postgres',
    seederStorage: 'sequelize',
    port: process.env.DATABASE_PORT || '5432',
    pool: {
      max: 20,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
    logging: false,
    encryptionKey: process.env.ENCRYPTION_KEY || 'test',
  },
};
